services:
  redis:
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASS=${REDIS_PASS}
    image: "redis:alpine"
    command: redis-server --requirepass ${REDIS_PASS}
    ports:
      - "6379:6379"
    volumes:
      - /redis-data:/var/lib/redis
      - /redis.conf:/usr/local/etc/redis/redis.conf
    restart: always

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - redis
    links:
      - redis

volumes:
  redis-data:
    driver: local
