version: "3.2"
services:
  redis:
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASS=${REDIS_PASS}
    image: "redis:alpine"
    command: redis-server --requirepass ${REDIS_PASS}
    ports:
      - "6379:6379"
    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      node_net:
        ipv4_address: 172.28.1.4
  web:
    build: .
    ports:
      - "80:80"
    depends_on:
      - redis


networks:
  node_net:
    driver: bridge
